import {StoryPlanSchema, type PublicManifest, type StoryPlan} from '../domain/schemas.js';

export const planFixtureStory = (manifest: PublicManifest): StoryPlan => {
  const eventIds = manifest.events.map((event) => event.id);
  const learningIds = manifest.learnings.map((learning) => learning.id);
  const scenes = [
    {
      id: 'scene_01', type: 'hook' as const, durationSeconds: 6, accent: '#FFCC66',
      headline: 'Football. Newsletters. Coffee. Then a hackathon.',
      body: 'One ordinary founder day became the story you are watching.',
      narration: 'Today started with football, newsletters, and coffee—and ended with the video you are watching.',
      evidenceIds: eventIds.slice(0, 2),
    },
    {
      id: 'scene_02', type: 'problem' as const, durationSeconds: 8, accent: '#FF7A90',
      headline: 'Builders are not content teams.',
      body: 'Writing, scripting, narrating, and editing turns building in public into a second job.',
      narration: 'Solo founders are builders, not full-time content creators. Sharing what we learn and ship becomes another time-consuming job.',
      evidenceIds: [],
    },
    {
      id: 'scene_03', type: 'moments' as const, durationSeconds: 8, accent: '#7FDBCA',
      headline: 'The raw material already exists.',
      body: 'Curated learning + decisions + progress',
      narration: 'But the raw material already exists in the useful things we read, the decisions we make, and the work we ship.',
      evidenceIds: [...eventIds, ...learningIds].slice(0, 4),
    },
    {
      id: 'scene_04', type: 'terminal' as const, durationSeconds: 11, accent: '#7AA2FF',
      headline: '$ founder demo default end-day --fixture',
      body: 'collect → normalize → filter → plan → compile',
      narration: 'So I built Founder Build in Public. One command turns founder-approved evidence into a structured story while keeping every workspace private by default.',
      evidenceIds: eventIds.slice(2),
    },
    {
      id: 'scene_05', type: 'outputs' as const, durationSeconds: 9, accent: '#C79AFF',
      headline: 'One story. Two review-ready drafts.',
      body: 'Founder Digest  +  Founder Reel',
      narration: 'It creates two drafts from the same public-safe manifest: a newsletter-style Founder Digest and a faceless Founder Reel.',
      evidenceIds: learningIds,
    },
    {
      id: 'scene_06', type: 'reveal' as const, durationSeconds: 8, accent: '#F9F871',
      headline: 'This video is the proof.',
      body: 'Scripted, planned, captioned, and rendered by the workflow.',
      narration: 'This script, scene plan, captions, and video were generated by that same workflow from sanitized fixture data.',
      evidenceIds: eventIds,
    },
    {
      id: 'scene_07', type: 'lesson' as const, durationSeconds: 6, accent: '#FFFFFF',
      headline: 'Keep building.',
      body: 'Let the content come from the work.',
      narration: 'Building in public should be an output of building—not another time-consuming job.',
      evidenceIds: [],
    },
  ];

  const voiceover = scenes.map((scene) => scene.narration).join(' ');
  return StoryPlanSchema.parse({
    title: 'From Reading to Building',
    theme: manifest.themeCandidates[0] ?? 'Building creates the story',
    hook: scenes[0]?.narration ?? 'The work already contains the story.',
    founderLesson: 'Building in public should be an output of building—not another time-consuming job.',
    nextStep: 'Make this workflow a repeatable daily habit.',
    targetDurationSeconds: 56,
    voiceover,
    scenes,
  });
};
